spring.application.name=user-service
server.port=8081

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

# DB Connection (MySQL)
spring.datasource.url=${USER_DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Logging
logging.level.org.springframework=INFO
jwt.secret=${JWT_SECRET:8gSd9w02sLq93jhzXM9vlAjf29vKLnzM2xVRmQZHuGfyTzYsg2uYap8v1RmM2HjZ}
#valid for 15 mins
jwt.expiration=900000
internal.jwt.secret=${INTERNAL_JWT_SECRET}
#valid for 60 mins
internal.jwt.expiration=3600000
# 7 days in milliseconds (7 * 24 * 60 * 60 * 1000)
jwt.refresh-expiration-ms=604800000

# 24 hours (in milliseconds)
spring.main.allow-bean-definition-overriding=true
logging.level.org.springframework.security=DEBUG

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Pagination defaults
spring.data.web.pageable.default-page-size=10
spring.data.web.pageable.max-page-size=100

# Email Configuration (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${GMAIL_USERNAME}
spring.mail.password=${GMAIL_APP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# OTP Configuration
otp.expiry.minutes=${OTP_EXPIRY_TIME}
otp.length=${OTP_LENGTH}

# Set to true in production with HTTPS, false for local localhost testing
jwt.cookie-secure=false


# Set twilio configurations
twilio.account.sid=${TWILIO_ACCOUNT_SID}
twilio.auth.token=${TWILIO_AUTH_TOKEN}
twilio.phone.number=${TWILIO_NUMBER}

# This turns 1715024400 into "2026-05-07T00:27:03Z", which is much easier to read.
spring.jackson.serialization.write-dates-as-timestamps=false
