# Service Identification
spring.application.name=product-service

# Server Port (you can change it)
server.port=8082

# MySQL Configuration
PRODUCT_DB_URL
spring.datasource.url=${PRODUCT_DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update

# JPA
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Eureka Discovery
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# JWT secret used for validation (must match auth-service)
jwt.secret=${JWT_SECRET}

# JWT secret key for internal service communication(to update stock after placing order)
internal.jwt.secret=${INTERNAL_JWT_SECRET}
internal.jwt.expiration=3600000

# ============ TIMEZONE CONFIG ============
spring.jackson.time-zone=UTC

