package com.shop.userservice.user_service.entity;

public enum ActivityType {
    REGISTRATION,
    LOGIN,
    LOGOUT,
    PROFILE_UPDATE,
    PASSWORD_CHANGE,
    ADMIN_ACTION,
    REGISTER_DRIVER,
    UPDATE_PASSWORD,
    UPDATE_DRIVER,
    DELETE_ACCOUNT,
    SOFT_DELETE_USER,
    RESTORE_USER,
    ACTIVATE_USER,
    DEACTIVATE_USER,
    DEACTIVATE_OWN_ACCOUNT,
    ADD_ADDRESS,
    UPDATE_ADDRESS,
    DELETE_ADDRESS,
    SET_DEFAULT_ADDRESS
}
